---
- name: Retrieve interfaces from Junos device
  hosts: junos_devices
  gather_facts: no
  connection: cli

  tasks:
    - name: Run 'show version' command
      junipernetworks.junos.junos_command:
        commands:
          - show version
      register: command_output

    - name: Display the command output
      ansible.builtin.debug:
        var: command_output.stdout_lines