---
collections:
  - name: juniper.device
  - name: junipernetworks.junos
    src: https://github.com/Juniper/ansible-junos-stdlib.git
    version: "2.0.0"  
  - name: junos-eznc
  - name: jxmlease
  - name: xmltodict