---
- name: Retrieve specific interface from a Junos device
  hosts: "{{ inventory_hostname }}"  # This ensures the specific host passed by AWX is used.
  gather_facts: no
  connection: local

  vars:
    interface_name: "{{ interface_name }}"  # Accept the interface name as a parameter

  tasks:
    - name: Run 'show interfaces terse' command for a specific interface
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces terse {{ interface_name }}
      register: command_output

    - name: Display the command output
      ansible.builtin.debug:
        var: command_output.stdout_lines