---
- name: Retrieve specific interface from a Junos device and display device name
  hosts: all
  gather_facts: no
  connection: local

  vars:
    device_interface_map:
      "172.18.3.13":
        interface: "ge-0/0/9.102"
        commands:
          - show interfaces ge-0/0/9.102
          - show interfaces terse ge-0/0/9.102
      "172.18.1.40":
        interface: "ge-0/0/9.102"
        commands:
          - show interfaces ge-0/0/9.102
          - show interfaces terse ge-0/0/9.102

  tasks:
    - name: Display inventory hostname
      ansible.builtin.debug:
        msg: "Inventory hostname: {{ inventory_hostname }}"

    - name: Retrieve device hostname
      junipernetworks.junos.junos_command:
        commands:
          - show version | match Hostname
      register: device_info

    - name: Extract the device hostname from the output
      ansible.builtin.set_fact:
        device_hostname: "{{ (device_info.stdout_lines[0] | select('search', 'Hostname:') | list)[0].split(':')[-1] | trim }}"
      when: device_info.stdout_lines is defined and device_info.stdout_lines | length > 0

    - name: Display the device hostname
      ansible.builtin.debug:
        msg: "Device: {{ device_hostname }}"

    - name: Check if the device is in the map
      ansible.builtin.set_fact:
        interface_info: "{{ device_interface_map[inventory_hostname] }}"
      when: inventory_hostname in device_interface_map

    - name: Run commands based on interface info
      junipernetworks.junos.junos_command:
        commands: "{{ interface_info.commands }}"
      register: command_outputs
      when: interface_info is defined

    - name: Display raw output for each command
      ansible.builtin.debug:
        msg: |
          Device: {{ device_hostname }}
          {% for output in command_outputs.stdout_lines %}
          {{ output }}
          {% endfor %}
      when: command_outputs is defined
