---
- name: Retrieve specific interface from a Junos device and display device name
  hosts: all
  gather_facts: no
  connection: local

  vars:
    device_interface_map:
      "172.18.3.13": "ge-0/0/9.102"
      "172.18.1.40": "ge-0/0/9.102"

  tasks:
    - name: Display inventory hostname
      ansible.builtin.debug:
        msg: "Inventory hostname: {{ inventory_hostname }}"

    - name: Retrieve device hostname
      junipernetworks.junos.junos_command:
        commands:
          - show version | match Hostname
      register: device_info

    - name: Extract the device hostname from the output
      ansible.builtin.set_fact:
        device_hostname: "{{ (device_info.stdout_lines[0] | select('search', 'Hostname:') | list)[0].split(':')[-1] | trim }}"
      when: device_info.stdout_lines is defined and device_info.stdout_lines | length > 0

    - name: Display the device hostname
      ansible.builtin.debug:
        msg: "Device: {{ device_hostname }}"

    - name: Check if the device is in the map
      ansible.builtin.set_fact:
        interface_name: "{{ device_interface_map[inventory_hostname] }}"
      when: inventory_hostname in device_interface_map

    - name: Run 'show interfaces' command for the specific interface
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces
      register: show_interfaces_output
      when: interface_name is defined

    - name: Run 'show interfaces terse' command for the specific interface
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces terse
      register: show_interfaces_terse_output
      when: interface_name is defined

    - name: Display the output of 'show interfaces'
      ansible.builtin.debug:
        msg: |
          Device: {{ device_hostname }}
          Show Interfaces:
          {{ show_interfaces_output.stdout_lines | join('\n') if show_interfaces_output.stdout_lines is defined else 'No output' }}

    - name: Display the output of 'show interfaces terse'
      ansible.builtin.debug:
        msg: |
          Device: {{ device_hostname }}
          Show Interfaces Terse:
          {{ show_interfaces_terse_output.stdout_lines | join('\n') if show_interfaces_terse_output.stdout_lines is defined else 'No output' }}
