---
- name: Traceroute from source to destination with specified routing instance
  hosts: 172.18.3.13
  gather_facts: no
  connection: local

  tasks:
    

    - name: Run traceroute command
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance KT_EPS044293T source 10.236.128.178 10.236.128.186"
      register: traceroute_output

    - name: Display traceroute results
      debug:
        var: traceroute_output.stdout_lines

    - name: Display full traceroute output for debugging
      debug:
        var: traceroute_output