---
- name: Traceroute from source to destination with specified routing instance
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  vars:
    src_ip: "{{ src_ip_address_variable }}"        # Source IP
    dest_ip: "{{ dest_ip_address_variable }}"      # Destination IP
    service_name: "{{ service_name }}"     # Routing instance name
  tasks:
    - name: Run traceroute command
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ service_name }} source {{ src_ip }} {{ dest_ip }}"
      register: traceroute_output

    - name: Display traceroute results
      debug:
        var: traceroute_output.stdout_lines

    - name: Display traceroute errors (if any)
      debug:
        var: traceroute_output.stderr

    - name: Display full traceroute output for debugging
      debug:
        var: traceroute_output