---
- name: Ping from source to destination with routing instance
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  vars:
    src_ip: "{{ src_ip_address_variable }}"      # Source IP
    dest_ip: "{{ dest_ip_address_variable }}"    # Destination IP
    service_name: "{{ service_name }}"

  tasks:
    - name: Show constructed traceroute command
      debug:
        msg: "Executing command: traceroute routing-instance {{ service_name }} source {{ src_ip }} {{ dest_ip }}"

    - name: Run traceroute command
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ service_name }} source {{ src_ip }} {{ dest_ip }}"
      register: traceroute_output

    - name: Display full traceroute output
      debug:
        var: traceroute_output

    - name: Test basic command
      junipernetworks.junos.junos_command:
        commands:
          - "show version"
      register: version_output

    - name: Display version output
      debug:
        var: version_output

    - name: Show routing instances
      junipernetworks.junos.junos_command:
        commands:
          - "show configuration routing-instances"
      register: routing_instances_output

    - name: Display routing instances
      debug:
        var: routing_instances_output