- name: Execute Traceroute on Juniper Router
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  tasks:
    - name: Run traceroute
      junipernetworks.junos.junos_rpc:
        rpc: "traceroute"
        args:
          routing-instance: "{{ routing_instance }}"
          source: "{{ source_ip }}"
          host: "{{ destination_ip }}"
        output: json
      register: traceroute_result

    - name: Display traceroute output
      debug:
        var: traceroute_result
    - name: Parse JSON/XML output
      community.general.json_query:
        data: "{{ traceroute_result.result }}"
        query: "your_json_query"  # Replace with your JSON query
      register: parsed_traceroute
    
    - name: Display parsed traceroute output
      debug:
        var: parsed_traceroute
    
