---
- name: Ping from source to destination with routing instance
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  vars:
    src_ip: "{{ src_ip_address_variable }}"      # Source IP
    dest_ip: "{{ dest_ip_address_variable }}"    # Destination IP
    service_name: "{{ service_name }} "
  tasks:
    - name: Run traceroute command
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ service_name }} source {{ src_ip }} {{ dest_ip }}"
        wait_for: 20
        display: true
      register: traceroute_output
    - name: Run traceroute 172.18.24.33
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute 172.18.24.33"
        wait_for: 20
        display: true
      register: traceroute2_output

    - name: Display traceroute results
      debug:
        var: traceroute_output.stdout_lines
    - name: Display traceroute results
      debug:
        var: traceroute2_output.stdout_lines