- name: Execute Traceroute on Juniper Router
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  tasks:
    - name: Run traceroute
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ routing_instance }} source {{ source_ip }} {{ destination_ip }}"
        timeout : 300
      register: traceroute_result

    - name: Display traceroute output
      debug:
        var: traceroute_result
