- name: Execute Traceroute on Juniper Router
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  tasks:
    - name: Run traceroute
      junipernetworks.junos.junos_rpc:
        rpc: "traceroute"
        args:
          routing-instance: "{{ routing_instance }}"
          source: "{{ source_ip }}"
          host: "{{ destination_ip }}"
        register: traceroute_result

    - name: Display traceroute output
      debug:
        var: traceroute_result.stdout_lines

    - name: Parse traceroute output
      community.general.xml:
        xmlstring: "{{ traceroute_result.stdout_lines }}"
        register: parsed_traceroute

    - name: Display parsed traceroute output
      debug:
        var: parsed_traceroute.results