---
- name: Ping from source to destination with routing instance KT_EPS044293T
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  vars:
    src_ip: "{{ src_ip_address_variable }}"      # Source IP
    dest_ip: "{{ dest_ip_address_variable }}"    # Destination IP
  tasks:
    - name: Run ping command
      junipernetworks.junos.junos_command:
        commands:
          - "ping {{ dest_ip }} source {{ src_ip }} routing-instance KT_EPS044293T"
      register: ping_output

    - name: Display ping results
      debug:
        var: ping_output.stdout_lines