- name: Execute Traceroute on Juniper Router
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  tasks:
    - name: Run traceroute
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ routing_instance }} source {{ source_ip }} {{ destination_ip }}"
        waitfor: 40
      register: traceroute_result

    - name: Display raw stdout
      debug:
        var: traceroute_result.stdout

    - name: Display raw stderr
      debug:
        var: traceroute_result.stderr