- name: Execute Traceroute on Juniper Router
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  tasks:
    - name: Run traceroute
      junipernetworks.junos.junos_rpc:
        rpc: "traceroute"
        args:
          routing-instance: "{{ routing_instance }}"
          source: "{{ source_ip }}"
          host: "{{ destination_ip }}"
        output: json
      register: traceroute_result

    - name: Display traceroute output
      debug:
        var: traceroute_result
    - name: Display specific traceroute fields
      debug:
        msg: "Traceroute to {{ destination_ip }} from {{ source_ip }} via {{ routing_instance }}: {{ traceroute_result.rpc_reply['traceroute-information']['traceroute-route'] }}"