---
- name: Execute traceroute in routing instance
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  tasks:
    - name: Run traceroute in the specified routing-instance
      junipernetworks.junos.junos_rpc:
        rpc: "traceroute"
        kwargs:
          routing-instance: "{{ service_name }}"
          source: "{{ src_ip_address_variable }}"
          destination: "{{ dest_ip_address_variable }}"
      register: traceroute_output

    - name: Display traceroute output
      debug:
        var: traceroute_output.stdout_lines

