---
- name: Ping from source to destination with routing instance
  hosts: 172.18.3.13
  gather_facts: no
  connection: local

  tasks:

    - name: Run traceroute to a specific IP
      junipernetworks.junos.junos_rpc:
        rpc: traceroute
        args:
            destination: "172.18.24.33"
      register: traceroute2_output
    - name: Display traceroute results for specific IP
      debug:
        var: traceroute2_output
