---
- name: Ping from source to destination with routing instance
  hosts: "{{ inventory_hostname }}"
  gather_facts: no
  connection: local
  vars:
    src_ip: "{{ src_ip_address_variable }}"      # Source IP
    dest_ip: "{{ dest_ip_address_variable }}"    # Destination IP
    service_name: "{{ service_name }}"

  tasks:
    - name: Run traceroute command with routing instance
      junipernetworks.junos.junos_rpc:
        rpc: traceroute
        args: 
          filter: 
            traceroute:
              routing-instance: "{{ service_name }}"
              source: "{{ src_ip }}"
              destination: "{{ dest_ip }}"
      register: traceroute_output

    - name: Run traceroute to a specific IP
      junipernetworks.junos.junos_rpc:
        rpc: traceroute
        args:
          filter:
            traceroute:
              destination: "172.18.24.33"
      register: traceroute2_output

    - name: Display traceroute results for routing instance
      debug:
        var: traceroute_output

    - name: Display traceroute results for specific IP
      debug:
        var: traceroute2_output
