---
- name: Execute traceroute on Juniper devices
  hosts: 172.18.3.13  # This is the group of devices; adjust as necessary
  gather_facts: no
  connection: local

  tasks:
    - name: Execute traceroute command
      junipernetworks.junos.junos_command:
        commands:
          - "traceroute routing-instance {{ service_name }} source {{ source_ip }} {{ destination_ip }}"
      register: traceroute_output
      vars:
        ansible_network_os: junipernetworks.junos.junos

    - name: Display traceroute results
      debug:
        var: traceroute_output.stdout_lines