---
- name: Check interface status on Juniper BTI7060 using Telnet
  hosts: juniper_bti
  gather_facts: no
  connection: local  # Or you can run on a remote machine with telnet installed

  tasks:
    - name: Run telnet command via shell
      ansible.builtin.shell: |
        telnet {{ inventory_hostname }} 3084 <<EOF
        {{ ansible_user }}
        {{ ansible_password }}
        show interface all
        exit
        EOF
      register: telnet_output

    - name: Display interface status
      ansible.builtin.debug:
        var: telnet_output.stdout_lines