---
- name: Execute command on devices and filter output
  hosts: junos_production_devices
  gather_facts: no
  connection: local

  vars:
    predefined_service_name: "KT_EPS044293T"  # Replace with your specific service name

  tasks:
    - name: Run command to match predefined service name
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces descriptions | match "{{ predefined_service_name }}"
      register: command_output

    - name: Display command output
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          Command Output:
          {{ command_output.stdout_lines}}
