---
- name: Execute command on devices and filter output
  hosts: junos_production_devices
  gather_facts: no
  connection: local

  vars:
    predefined_service_name: "KT_EPS044293T"  # Replace with your specific service name

  tasks:
    - name: Run command to retrieve interface descriptions
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces description
      register: command_output

    - name: Filter command output to include only lines with the predefined service name
      set_fact:
        filtered_output: >-
          {{
            command_output.stdout_lines |
            flatten |
            select('search', predefined_service_name) |
            list
          }}

    - name: Display filtered command output
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          Filtered Command Output:
          {{ filtered_output | join('\n') }}
