---
- name: Execute command on devices and filter output
  hosts: junos_production_devices
  gather_facts: no
  connection: local

  vars:
    predefined_service_name: "KT_EPS044293T"  # Replace with your specific service name

  tasks:
    - name: Retrieve interface descriptions from each device
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces description
      register: interface_descriptions

    - name: Filter output for predefined service name
      set_fact:
        filtered_output: >-
          {{
            interface_descriptions.stdout_lines |
            flatten |
            select('search', predefined_service_name) |
            list
          }}

    - name: Display filtered output for each device
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          Filtered Command Output:
          {{ filtered_output | join('\n') }}
