---
- name: Execute command on devices and display output
  hosts: junos_production_devices
  gather_facts: no
  connection: local

  vars:
    predefined_service_name: "KT_EPS044293T"  # Replace with your specific service name

  tasks:
    - name: Retrieve interface descriptions from each device
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces descriptions | match "{{ predefined_service_name }}"
      register: interface_descriptions

    - name: Debug raw interface descriptions output
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          Command Output:
          {{ interface_descriptions.stdout_lines | join('\n') }}