---
- name: Retrieve and Display Information from Junos Devices
  hosts: 172.18.3.13, 172.18.1.40, 192.168.75.116, 172.18.24.9
  gather_facts: no
  connection: local

  tasks:
    - name: Run all commands
      junipernetworks.junos.junos_command:
        commands:
          - show system information
          - show bgp summary instance KT_EPS044293T
          - show route summary table KT_EPS044293T.inet.0
          - show route table KT_EPS044293T.inet.0
      register: all_commands_output

    - name: Display all command outputs
      ansible.builtin.debug:
        msg: |
          {
            "item.stdout_lines": [
              {{ all_commands_output.stdout_lines | to_nice_yaml }}
            ],
            "_ansible_verbose_always": true,
            "_ansible_no_log": false,
            "changed": false,
            "item": {
              "commands": [
                "show system information",
                "show bgp summary instance KT_EPS044293T",
                "show route summary table KT_EPS044293T.inet.0",
                "show route table KT_EPS044293T.inet.0"
              ]
            },
            "ansible_loop_var": "item"
          }
