---
- name: Retrieve and Display Information from Junos Devices
  hosts: 172.18.3.13, 172.18.1.40, 192.168.75.116, 172.18.24.9
  gather_facts: no
  connection: local

  tasks:
    - name: Run all commands
      junipernetworks.junos.junos_command:
        commands:
          - show system information
          - show bgp summary instance KT_EPS044293T
          - show route summary table KT_EPS044293T.inet.0
          - show route table KT_EPS044293T.inet.0
      register: all_commands_output

    - name: Display all command outputs in structured format
      ansible.builtin.debug:
        msg: |
          {
            "device": "{{ inventory_hostname }}",
            "commands": [
              {
                "command": "show system information",
                "output": {{ all_commands_output.stdout[0] | to_nice_yaml }}
              },
              {
                "command": "show bgp summary instance KT_EPS044293T",
                "output": {{ all_commands_output.stdout[1] | to_nice_yaml }}
              },
              {
                "command": "show route summary table KT_EPS044293T.inet.0",
                "output": {{ all_commands_output.stdout[2] | to_nice_yaml }}
              },
              {
                "command": "show route table KT_EPS044293T.inet.0",
                "output": {{ all_commands_output.stdout[3] | to_nice_yaml }}
              }
            ]
          }