---
- name: Retrieve interfaces from Junos device
  hosts: 172.18.3.13, 172.18.1.40, 192.168.75.116, 172.18.24.9
  gather_facts: no
  connection: local

  tasks:
    - name: Run 'show system information' command
      junipernetworks.junos.junos_command:
        commands:
          - show system information
      register: system_info

    - name: Extract the hostname from system information
      set_fact:
        device_hostname: "{{ item.split(': ')[1] }}"
      loop: "{{ system_info.stdout_lines }}"
      when: "'Hostname' in item"

    - name: Ensure device_hostname is defined
      ansible.builtin.fail:
        msg: "Hostname not found in system information"
      when: device_hostname is not defined

    - name: Display the hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ device_hostname }}"

    - name: Run 'show route summary table KT_EPS044293T.inet.0' command
      junipernetworks.junos.junos_command:
        commands:
          - show route summary table KT_EPS044293T.inet.0
      register: command_output

    - name: Display the command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
