---
- name: Retrieve and Display Information from Junos Devices
  hosts: 172.18.3.13, 172.18.1.40, 192.168.75.116, 172.18.24.9
  gather_facts: no
  connection: local

  tasks:
    - name: Run all commands
      junipernetworks.junos.junos_command:
        commands:
          - show system information
          - show bgp summary instance KT_EPS044293T
          - show route summary table KT_EPS044293T.inet.0
          - show route table KT_EPS044293T.inet.0
      register: all_commands_output

    - name: Display all command outputs
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          Command: show system information
          Output: {{ all_commands_output.stdout[0] }}
          
          Command: show bgp summary instance KT_EPS044293T
          Output: {{ all_commands_output.stdout[1] }}

          Command: show route summary table KT_EPS044293T.inet.0
          Output: {{ all_commands_output.stdout[2] }}

          Command: show route table KT_EPS044293T.inet.0
          Output: {{ all_commands_output.stdout[3] }}