---
- name: Run traceroute on a specific Juniper device with extended timeout
  hosts: "{{ inventory_hostname }}"
  gather_facts: no

  # Set the timeout for the SSH command to 120 seconds
  tasks:
    - name: Execute traceroute to a destination IP
      junipernetworks.junos.junos_command:
        commands:
          - traceroute {{ destination_ip }} wait 1 ttl 20
      register: traceroute_output

    - name: Display traceroute result
      debug:
        var: traceroute_output.stdout_lines
